apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: relicstaurants
  name: relicstaurants
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: relicstaurants
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: relicstaurants
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
          image: relicstaurants
          name: relicstaurants
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
